name: Test secrets
on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check configured flags (no secret values are printed)
        run: |
          echo "SUPABASE_PRODUCTION_REF set: ${{ secrets.SUPABASE_PRODUCTION_REF != '' }}"
          echo "SUPABASE_STAGING_REF set: ${{ secrets.SUPABASE_STAGING_REF != '' }}"
          echo "SUPABASE_SERVICE_KEY set: ${{ secrets.SUPABASE_SERVICE_KEY != '' }}"
          echo "DISCORD_WEBHOOK_DEPLOYMENTS set: ${{ secrets.DISCORD_WEBHOOK_DEPLOYMENTS != '' }}"
          echo "DISCORD_WEBHOOK_ALERTS set: ${{ secrets.DISCORD_WEBHOOK_ALERTS != '' }}"

      - name: Fail if SUPABASE_PRODUCTION_REF is missing
        if: ${{ secrets.SUPABASE_PRODUCTION_REF == '' }}
        run: |
          echo "ERROR: SUPABASE_PRODUCTION_REF is not configured."
          exit 1